services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  migration:
    build: ./services/backend
    command: >
      bash -c "python3 wait_for_mysql.py &&
               python3 manage.py migrate"
    environment:
      - DJANGO_SECRET_KEY=local
      - MYSQL_DATABASE=app_db
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    volumes:
      - ./services/backend:/code
    depends_on:
      - db

  seed:
    build: ./services/backend
    command: >
      bash -c "python3 wait_for_mysql.py &&
               python3 manage.py seed"
    environment:
      - DJANGO_SECRET_KEY=local
      - MYSQL_DATABASE=app_db
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    volumes:
      - ./services/backend:/code
    depends_on:
      - migration

  users:
    build: ./services/backend
    command: >
      bash -c "python3 wait_for_mysql.py &&
               python3 manage.py create_admin &&
               python3 manage.py create_test_user"
    environment:
      - DJANGO_SECRET_KEY=local
      - MYSQL_DATABASE=app_db
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - SUPERUSER_EMAIL=admin@admin.com
      - SUPERUSER_PASS=admin1234
      - SUPERUSER_USERNAME=admin
      - USERNAME=ihribernik
      - EMAIL=ihribernik@notadmin.com
      - PASS=not-admin-1234
    volumes:
      - ./services/backend:/code
    depends_on:
      - migration
      - seed

  backend:
    build: ./services/backend
    environment:
      - DJANGO_SECRET_KEY=local
      - MYSQL_DATABASE=app_db
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - PORT=8000
      - DJANGO_SETTINGS_MODULE=backend.config
      - DJANGO_CONFIGURATION=Local
    ports:
      - "8000:8000"
    volumes:
      - ./services/backend:/code
    depends_on:
      - db
      - migration
      - seed
      - users

  frontend:
    build: ./services/frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=not-admin-1234
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_DJANGO_API_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  mysql_data: